name = "DoubleEnded"
uuid = "1bc4e7c2-c1e1-11e9-03fe-315bbef43fde"
authors = ["John Tinnerholm johti <johti17@liu.se>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ExportAll = "ad2082ca-a69e-11e9-38fa-e96309a31fe4"
ImmutableList = "4a558cac-c1ed-11e9-20da-3584bcd8709a"

[compat]
julia = "1.1"
